### ISSUE TITLE
Example in the documentation cannot be copied into ipython

### ISSUE THREAD

**Issue by rychallener** [pcubillos/MCcubed#15]
Some of the characters in the documentation PDF can't be copied into Python. Likely this is just an issue with the tex file being compiled, but it seems that the hyphen (-) and single quote (') get messed up somehow. 

Also some spacing issues with the sys.path.append() commands. The PDF has some spaces in the path that shouldn't be there.

**Comment by rychallener** [comment]
Also the following line:

sys.path.append("./examples/example01/")

Should be:

sys.path.append("./examples")

Or maybe you need both lines. But you definitely need the second one.

**Comment by pcubillos** [comment]
Yes, I was dealing with the pdf-copy-paste issue one day, but I didn't get anywhere. It may not have a (simple) solution.
The only thing that found to work is to kee

On the second issue, you are right!, I moved files around and forgot to update the documentation. Since this is a separated issue, I'll create a new one to separate them.

Thanks.

**Comment by joeharr4** [comment]
> The only thing that found to work is to kee


This seems to stop in mid-

--jh--
X-Spam-Status: No, score=-4.8 required=3.0 tests=BAYES_00,HTML_IMAGE_ONLY_12,
	HTML_MESSAGE,RCVD_IN_DNSWL_HI,RCVD_IN_MSPIKE_H3,RCVD_IN_MSPIKE_WL,
	T_DKIM_INVALID autolearn=ham autolearn_force=no version=3.4.0
Date: Fri, 20 Nov 2015 12:23:41 -0800

**Comment by rychallener** [comment]
That appears to be a github bug, or Patricio changed it after github sent out the email.

**Comment by pcubillos** [comment]
Ahh, yes I edited the post when I saw it.
